import { execSync } from 'child_process'
import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

let hash
try {
  hash = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim()
} catch {
  hash = 'dev'
}

const content = `// Auto-generated by scripts/generate-version.mjs — do not edit
export const APP_VERSION = '${hash}'
`
writeFileSync(resolve(__dirname, '..', 'src', 'lib', 'version.ts'), content)
